<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Chi tiết doanh thu chi nhánh</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<link rel="stylesheet" href="${ctx}/assets/css/admin/variables.css"><link rel="stylesheet" href="${ctx}/assets/css/admin/base.css"><link rel="stylesheet" href="${ctx}/assets/css/admin/components.css"><link rel="stylesheet" href="${ctx}/assets/css/admin/tables.css"><link rel="stylesheet" href="${ctx}/assets/css/admin/forms.css">
<style>.revenue-page{max-width:1440px;margin:0 auto;padding:32px}.revenue-summary{display:flex;gap:24px;align-items:center;justify-content:space-between;margin:16px 0;padding:20px;border:1px solid rgba(229,9,20,.35);border-radius:12px;background:rgba(229,9,20,.08)}.revenue-summary strong{font-size:28px;color:var(--primary-light)}.revenue-filter{display:flex;gap:12px;align-items:end;margin:18px 0}.revenue-filter label{display:grid;gap:6px;font-size:12px;font-weight:700;color:var(--n-500)}.revenue-filter .rv-input[type=date]{color-scheme:dark}.pager{display:flex;justify-content:flex-end;gap:14px;padding:14px;color:var(--n-500)}.pager a{color:var(--primary-light);font-weight:700;text-decoration:none}@media(max-width:650px){.revenue-page{padding:16px}.revenue-filter{flex-wrap:wrap}.revenue-summary{align-items:flex-start;flex-direction:column}}</style>
</head><body><main class="revenue-page">
<a class="rv-btn rv-btn--ghost" href="${ctx}/manager/dashboard"><i class="bi bi-arrow-left"></i> Quay lại dashboard</a>
<h1 class="rv-page-title" style="margin-top:18px">Chi tiết doanh thu chi nhánh</h1><p class="rv-page-subtitle">Chỉ gồm giao dịch thanh toán thành công tại chi nhánh bạn quản lý.</p>
<form class="revenue-filter" method="get" action="${ctx}/manager/revenue"><label>Từ ngày<input class="rv-input" type="date" name="fromDate" value="${fromDate}"></label><label>Đến ngày<input class="rv-input" type="date" name="toDate" value="${toDate}"></label><button class="rv-btn rv-btn--primary" type="submit"><i class="bi bi-funnel-fill"></i> Lọc</button><a class="rv-btn rv-btn--ghost" href="${ctx}/manager/revenue">Xóa lọc</a></form>
<section class="revenue-summary"><div><span>DOANH THU THỰC NHẬN</span><strong><fmt:formatNumber value="${revenue.netRevenue}" type="number" maxFractionDigits="0"/> đ</strong></div><span>Vé: <b><fmt:formatNumber value="${revenue.ticketRevenue}" type="number" maxFractionDigits="0"/> đ</b></span><span>F&amp;B: <b><fmt:formatNumber value="${revenue.fnbRevenue}" type="number" maxFractionDigits="0"/> đ</b></span><span>Giảm giá: <b><fmt:formatNumber value="${revenue.discountAmount}" type="number" maxFractionDigits="0"/> đ</b></span></section>
<div class="rv-table-wrap"><table class="rv-table"><thead><tr><th>Thanh toán lúc</th><th>Booking</th><th>Phim</th><th>Nguồn / phương thức</th><th style="text-align:right">Vé</th><th style="text-align:right">F&amp;B</th><th style="text-align:right">Giảm giá</th><th style="text-align:right">Thực nhận</th></tr></thead><tbody><c:choose><c:when test="${empty transactions}"><tr><td colspan="8" style="text-align:center;padding:32px">Không có giao dịch phù hợp.</td></tr></c:when><c:otherwise><c:forEach items="${transactions}" var="t"><tr><td><fmt:formatDate value="${t.paidAt}" pattern="dd/MM/yyyy HH:mm"/></td><td>#<c:out value="${t.bookingId}"/></td><td><c:out value="${t.movieTitle}"/></td><td><c:out value="${t.source}"/> · <c:out value="${t.paymentMethod}"/></td><td style="text-align:right"><fmt:formatNumber value="${t.ticketAmount}" type="number" maxFractionDigits="0"/> đ</td><td style="text-align:right"><fmt:formatNumber value="${t.fnbAmount}" type="number" maxFractionDigits="0"/> đ</td><td style="text-align:right"><fmt:formatNumber value="${t.discountAmount}" type="number" maxFractionDigits="0"/> đ</td><td style="text-align:right;font-weight:800"><fmt:formatNumber value="${t.netAmount}" type="number" maxFractionDigits="0"/> đ</td></tr></c:forEach></c:otherwise></c:choose></tbody></table></div>
<div class="pager"><span>Trang ${page}/${totalPages} · ${total} giao dịch</span><c:if test="${page gt 1}"><c:url var="prev" value="/manager/revenue"><c:param name="fromDate" value="${fromDate}"/><c:param name="toDate" value="${toDate}"/><c:param name="page" value="${page-1}"/></c:url><a href="${prev}">← Trước</a></c:if><c:if test="${page lt totalPages}"><c:url var="next" value="/manager/revenue"><c:param name="fromDate" value="${fromDate}"/><c:param name="toDate" value="${toDate}"/><c:param name="page" value="${page+1}"/></c:url><a href="${next}">Sau →</a></c:if></div>
</main></body></html>
