<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<c:set var="pageTitle" value="Quan ly the loai" scope="request" />
<%@ include file="/pages/shared/header-admin.jsp" %>
<%@ include file="/pages/shared/sidebar-admin.jsp" %>
<div class="rv-page-header"><div class="rv-page-header__left"><div class="rv-breadcrumb"><a href="${ctx}/admin/dashboard">Dashboard</a><i class="bi bi-chevron-right rv-breadcrumb__sep"></i><span class="rv-breadcrumb__current">The loai</span></div><h1 class="rv-page-title">Quan ly the loai</h1><p class="rv-page-subtitle">Them, sua va an the loai phim trong he thong.</p></div><div class="rv-page-header__right"><a href="${ctx}/admin/categories?action=new" class="rv-btn rv-btn--primary"><i class="bi bi-plus-lg"></i>Them the loai</a></div></div>
<div class="rv-card"><div class="rv-table-responsive"><table class="rv-table"><thead><tr><th style="width:70px;">ID</th><th>Ten</th><th>Mo ta</th><th style="width:140px;">Trang thai</th><th style="width:140px;text-align:center;">Thao tac</th></tr></thead><tbody><c:forEach var="c" items="${categories}"><tr><td>${c.id}</td><td><strong><c:out value="${c.name}"/></strong></td><td><c:out value="${empty c.description ? '-' : c.description}"/></td><td><span class="rv-badge ${c.status == 'ACTIVE' ? 'rv-badge--nowshowing' : 'rv-badge--ended'}"><c:out value="${c.status}"/></span></td><td><div class="d-flex align-items-center justify-content-center gap-2"><a href="${ctx}/admin/categories?action=edit&id=${c.id}" class="rv-btn rv-btn--ghost rv-btn--icon" style="border:none"><i class="bi bi-pencil-square"></i></a><a href="${ctx}/admin/categories?action=delete&id=${c.id}" class="rv-btn rv-btn--ghost rv-btn--icon" style="color:var(--danger);border:none" data-confirm data-confirm-title="An the loai?" data-confirm-message="The loai se duoc chuyen sang INACTIVE." data-confirm-type="warning" data-confirm-text="An"><i class="bi bi-trash3-fill"></i></a></div></td></tr></c:forEach></tbody></table></div></div>
</main></div></body></html>
